[workspace]
resolver = "2"
members = [
    "crates/stego-core",
    "crates/stego-cli",
    "crates/stego-ffi",
    "apps/desktop/src-tauri",
]

[workspace.package]
version = "0.4.0"
edition = "2021"
license = "MIT"
authors = ["Saeed shamsi"]

[workspace.dependencies]
stego-core = { path = "crates/stego-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
